version: '3.7'

services:
  server:
    image: tornadocash/relayer
    restart: always
    command: 'server'
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on: [redis]

  txWorker:
    image: tornadocash/relayer
    restart: unless-stopped
    command: 'txWorker'
    env_file: .env
    depends_on: [redis]

  healthWorker:
    image: tornadocash/relayer
    restart: unless-stopped
    command: 'healthWorker'
    env_file: .env
    depends_on: [redis]

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - redis:/data

volumes:
  redis:
